### ISSUE TITLE
How to produce or get data for trainning

### ISSUE THREAD

**Issue by UESTCgan** [seiichiinoue/odcnn#2]
@seiichiinoue  It is a very nice work! Recently, I'm also working on Onset Detection. Look forword to communicating with you! I want to reprodeuce your project. But it seems that there is no data for trainning. 
  
![image](https://user-images.githubusercontent.com/40649244/53391614-e71e9500-39d1-11e9-9f22-f0072f0ed063.png)
![image](https://user-images.githubusercontent.com/40649244/53391635-fc93bf00-39d1-11e9-9b33-b129ff980c2b.png)

Do you use the Bock dataset or [Jingju](https://drive.google.com/drive/folders/17mo5FuWyEHkCFRExKRLGXFcQk2n-jMEW) dataset? I want to know  how to produce or get data for trainning.

**Comment by seiichiinoue** [comment]
@UESTCgan Thank you for contacting me.
Due to the large size of the data, some data files necessary for learning have not been uploaded.
**Please wait a moment as I upload it soon** using LFS or something like that.
By the way, since this is a model that generates the score(notes) of the game "Taiko no Tatsujin", I use the music data prepared for the "Taiko no Tatsujin" music score, is [here](https://taikosanjiro-humenroom.net/)

**Comment by UESTCgan** [comment]
@seiichiinoue I've got it.Thanks for your so quick reply! Did you try the dataset from [Dance Dance Convolution](https://arxiv.org/pdf/1703.06891.pdf) which is also from games? If I use the DDC dataset or Bock dataset, will the model also work?

**Comment by seiichiinoue** [comment]
If you want to learn music data after downloading it, please put music data in data/train directory for each artist. and structure of this directory is must be...
```
data -- train --- artist name1 --- music data file
                                               |
                                               |-- notes file(.tja)
```

**Comment by seiichiinoue** [comment]
@UESTCgan I guess it probably will not work. As I explained earlier, it is because I am making a model for "Taiko no Tatsujin".
However, since I am making a model by imitating "Improved Musical Onset Detection wtih CNN", I think that you can learn using the bock dataset.

Hmm, Should I rebuild the model to accommodate various data ...?

**Comment by seiichiinoue** [comment]
sorry for the mistake

**Comment by UESTCgan** [comment]
@seiichiinoue After you uploaded dataset，first ,I try to train the model with your dataset and reproduce your work.  And then, I will try other dataset. Thanks again for your reply! If you are convenient to rebuild the model to accommodate various data, look forward for your work !  When I get the my result of trainning, I will communicate with you again.

**Comment by seiichiinoue** [comment]
@UESTCgan I'm sorry, uploading wasn't possible because the compressed data size exceeds the upper limit of git-lfs. 
By the way, I think I can upload data with reduced size, so will I upload it? (The result of learning should not change so much)

**Comment by UESTCgan** [comment]
@seiichiinoue Thanks for your uploading data. I want to get a part of your data. So I look forward your uploading after reducing size.

**Comment by seiichiinoue** [comment]
@UESTCgan uploaded training data file at `data/pickles/`, watch it.

**Comment by UESTCgan** [comment]
@seiichiinoue Thanks again!

**Comment by UESTCgan** [comment]
@seiichiinoue  I want to know how to produce the './data/pickles/test_data.pickle'
![image](https://user-images.githubusercontent.com/40649244/53614460-06f1cb00-3c15-11e9-8438-2de097fa589b.png)

When I run " python3 music_processor.py "test" ",  I get an error .
**RuntimeError: Error opening './data/test/umaru.ogg': File contains data in an unimplemented format.**

![image](https://user-images.githubusercontent.com/40649244/53614557-4fa98400-3c15-11e9-8a11-cb879b2774f0.png)

**Comment by seiichiinoue** [comment]
What version of SoundFile are you using?
I'm using `SoundFile == 0.10.2`

**Comment by seiichiinoue** [comment]
I was able to run `music_processor test` successfully in my environment...

**Comment by seiichiinoue** [comment]
By the way, if you couldn’t solve it, I uploaded test data under `data/pickles`, so please use it.

**Comment by UESTCgan** [comment]
@seiichiinoue Thank you ! I make sure that SoundFile is 0.10.2 . Maybe, there is other difference in my environment. I have solve the problem by transfer the ".ogg" file to ".wav"。

**Comment by seiichiinoue** [comment]
ok, after you train it, tell me result please!
