### ISSUE TITLE
music_processor.py:227: NumbaWarning:

### ISSUE THREAD

**Issue by realchrisolin** [seiichiinoue/odcnn#9]
```
music_processor.py:227: NumbaWarning:
Compilation is falling back to object mode WITH looplifting enabled because Function "multi_fft_and_melscale" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at music_processor.py (230)
```
https://github.com/seiichiinoue/cnn-for-musical-onset-detection/blob/07eaba4b8398de0b248a4353165d9797fc76a7d7/music_processor.py#L227

I'm not exactly familiar with the `@jit` decorator and I'm not sure what it's doing or the terms in the warning without doing some research, but I still wanted to report it for the record. It doesn't appear to be causing a problem right now and if it starts affecting the accuracy of my models, I can troubleshoot it myself and put in a PR.

**Comment by seiichiinoue** [comment]
https://numba.pydata.org/numba-doc/dev/user/troubleshoot.html
